Repository FlexesFarkas/ProgTech_Beadando, pull requests merged in 2024-05, with the labels that each got.

#79 RT - Hibajavítás
  Docs/Rendszerterv.md
Labels: documentation

#78 41 tesztelés 2
  Project/Kiosk/KioskBackend/kiosk_db.sqlite
  Project/Kiosk/KioskBackend/pom.xml
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/Database.java
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/exceptions/DatabaseFailedToResetException.java
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/exceptions/NotEnoughIngredietnsException.java
  Project/Kiosk/KioskBackend/src/test/java/DatabaseTest.java
Labels: enhancement

#75 AB hibajavítás és reset
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/Database.java
Labels: bug, enhancement

#76 Ab hibajavitas 2
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/Database.java
Labels: bug, enhancement

#82 81 kosrba ments
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/CartActions.java
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/food/IngridientDecorator.java
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/food/decorators/Cheese.java
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/food/decorators/Cucumber.java
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/food/decorators/Tomato.java
Labels: bug, enhancement

#84 Függvény kosár összár lekéréséhez
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/CartActions.java
Labels: enhancement

#85 Frontend etelvalasztas
  Project/Kiosk/KioskBackend/src/main/java/module-info.java
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/Database.java
  Project/Kiosk/KioskBackend/src/main/java/org/kiosk/Main.java
  Project/Kiosk/KioskFrontend/src/main/java/org/kiosk/kioskfrontend/OrderController.java
  Project/Kiosk/KioskFrontend/src/main/resources/org/kiosk/kioskfrontend/SelectOrderType.fxml
  Project/Kiosk/KioskFrontend/target/classes/org/kiosk/kioskfrontend/SelectOrderType.fxml
  Project/kiosk_db.sqlite
Labels: enhancement

#86 44 frontend hozzval kezels
  Project/Kiosk/KioskFrontend/src/main/java/org/kiosk/kioskfrontend/OrderController.java
  Project/Kiosk/KioskFrontend/src/main/resources/org/kiosk/kioskfrontend/SelectOrderType.fxml
  Project/Kiosk/KioskFrontend/target/classes/org/kiosk/kioskfrontend/SelectOrderType.fxml
Labels: enhancement

#93 frontend unit tesztek
  Project/Kiosk/KioskBackend/src/test/java/DatabaseTest.java
  Project/Kiosk/KioskFrontend/src/main/java/org/kiosk/kioskfrontend/OrderController.java
  Project/Kiosk/KioskFrontend/src/test/java/org/kiosk/kioskfrontend/OrderControllerTest.java
  Project/kiosk_db.sqlite
Labels: enhancement
